import { QuizQuestion } from "@/types";

export const fallbackQuizQuestions: QuizQuestion[] = [
  {
    id: "q_skin_type",
    order: 1,
    title: "¿Cómo describirías la sensación de tu piel a lo largo del día?",
    subtitle: "Selecciona la opción que mejor represente tu tipo de piel habitual.",
    type: "single",
    active: true,
    options: [
      {
        id: "opt_st_dry",
        questionId: "q_skin_type",
        label: "Seca o Tirante",
        description: "Siento rigidez, falta de humedad o zonas con descamación.",
        icon: "🌵",
        value: "dry",
        shotWeights: {
          "shot-hidra-power": 6,
          "shot-piel-tranquila": 3,
          "shot-ojos-fresh": 2,
        },
        moodWeights: { Hydrated: 5, Calm: 2 },
      },
      {
        id: "opt_st_oily",
        questionId: "q_skin_type",
        label: "Grasa o con Brillo Constante",
        description: "Brillo evidente en todo el rostro y tendencia a poros visibles.",
        icon: "✨",
        value: "oily",
        shotWeights: {
          "shot-bye-brotes": 6,
          "shot-piel-smooth": 4,
          "shot-adios-manchitas": 2,
        },
        moodWeights: { Clean: 5, Firm: 2 },
      },
      {
        id: "opt_st_combo",
        questionId: "q_skin_type",
        label: "Mixta",
        description: "Zona T (frente, nariz, barbilla) con grasa y mejillas normales o secas.",
        icon: "⚖️",
        value: "combination",
        shotWeights: {
          "shot-hidra-power": 4,
          "shot-piel-smooth": 4,
          "shot-adios-manchitas": 3,
        },
        moodWeights: { Glow: 4, Hydrated: 3 },
      },
      {
        id: "opt_st_sensitive",
        questionId: "q_skin_type",
        label: "Sensible o Reactiva",
        description: "Enrojece con facilidad, arde con ciertos activos o ante el clima.",
        icon: "🌸",
        value: "sensitive",
        shotWeights: {
          "shot-piel-tranquila": 8,
          "shot-hidra-power": 3,
        },
        moodWeights: { Calm: 6 },
      },
      {
        id: "opt_st_normal",
        questionId: "q_skin_type",
        label: "Equilibrada o Normal",
        description: "Ni muy seca ni muy grasa, busco mantener mi luminosidad y prevenir.",
        icon: "🫧",
        value: "normal",
        shotWeights: {
          "shot-adios-manchitas": 4,
          "shot-ojos-fresh": 4,
          "shot-hidra-power": 3,
        },
        moodWeights: { Glow: 5, Firm: 3 },
      },
    ],
  },
  {
    id: "q_concerns",
    order: 2,
    title: "¿Cuáles son tus principales prioridades o preocupaciones?",
    subtitle: "Puedes seleccionar hasta 2 prioridades principales.",
    type: "multi",
    active: true,
    options: [
      {
        id: "opt_c_dark_spots",
        questionId: "q_concerns",
        label: "Manchas & Marcas Post-Acné",
        description: "Hiperpigmentación, marcas oscuras o tono apagado/desigual.",
        icon: "🎯",
        value: "darkSpots",
        shotWeights: {
          "shot-adios-manchitas": 8,
          "shot-piel-smooth": 3,
        },
        moodWeights: { Glow: 6 },
      },
      {
        id: "opt_c_dehydration",
        questionId: "q_concerns",
        label: "Deshidratación & Falta de Jugosidad",
        description: "Piel apagada que necesita el efecto hidratado 'Glass Skin'.",
        icon: "💧",
        value: "dehydration",
        shotWeights: {
          "shot-hidra-power": 8,
          "shot-ojos-fresh": 3,
        },
        moodWeights: { Hydrated: 6 },
      },
      {
        id: "opt_c_breakouts",
        questionId: "q_concerns",
        label: "Granitos & Brotes Puntuales",
        description: "Imperfecciones activas, puntos negros o exceso de sebo.",
        icon: "⚡",
        value: "acne",
        shotWeights: {
          "shot-bye-brotes": 8,
          "shot-piel-smooth": 3,
        },
        moodWeights: { Clean: 6 },
      },
      {
        id: "opt_c_redness",
        questionId: "q_concerns",
        label: "Rojeces & Barrera Dérmica Débil",
        description: "Irritación, ardor o sensación de piel sensibilizada.",
        icon: "🌿",
        value: "redness",
        shotWeights: {
          "shot-piel-tranquila": 8,
          "shot-hidra-power": 3,
        },
        moodWeights: { Calm: 6 },
      },
      {
        id: "opt_c_eyes",
        questionId: "q_concerns",
        label: "Ojeras, Bolsas & Mirada Cansada",
        description: "Líneas de expresión perioculares, pigmentación o hinchazón.",
        icon: "👁️",
        value: "eyes",
        shotWeights: {
          "shot-ojos-fresh": 8,
          "shot-piel-smooth": 2,
        },
        moodWeights: { Firm: 5, Glow: 3 },
      },
      {
        id: "opt_c_texture",
        questionId: "q_concerns",
        label: "Textura Irregular & Poros Dilatados",
        description: "Relieve irregular, rugosidad o pérdida de elasticidad.",
        icon: "🪄",
        value: "texture",
        shotWeights: {
          "shot-piel-smooth": 8,
          "shot-bye-brotes": 2,
        },
        moodWeights: { Firm: 6, Clean: 3 },
      },
    ],
  },
  {
    id: "q_skin_mood",
    order: 3,
    title: "¿Cuál es el 'Skin Mood' o acabado que deseas alcanzar?",
    subtitle: "Elige la meta visual y sensitiva para tu piel.",
    type: "single",
    active: true,
    options: [
      {
        id: "opt_mood_glow",
        questionId: "q_skin_mood",
        label: "Glow Radiante",
        description: "Luminosidad saludable, tono homogéneo y piel reflectante.",
        icon: "✨",
        value: "Glow",
        shotWeights: {
          "shot-adios-manchitas": 5,
          "shot-hidra-power": 4,
          "shot-ojos-fresh": 3,
        },
        moodWeights: { Glow: 7 },
      },
      {
        id: "opt_mood_calm",
        questionId: "q_skin_mood",
        label: "Calm & Confort",
        description: "Piel serena, libre de rojez y con barrera fortalecida.",
        icon: "🌿",
        value: "Calm",
        shotWeights: {
          "shot-piel-tranquila": 7,
          "shot-hidra-power": 3,
        },
        moodWeights: { Calm: 7 },
      },
      {
        id: "opt_mood_clean",
        questionId: "q_skin_mood",
        label: "Clean & Equilibrada",
        description: "Sensación fresca, poros limpios y control de imperfecciones.",
        icon: "🍃",
        value: "Clean",
        shotWeights: {
          "shot-bye-brotes": 6,
          "shot-piel-smooth": 4,
        },
        moodWeights: { Clean: 7 },
      },
      {
        id: "opt_mood_hydrated",
        questionId: "q_skin_mood",
        label: "Hydrated & Jugosa",
        description: "Elasticidad, máxima retención de agua y suavidad al tacto.",
        icon: "💧",
        value: "Hydrated",
        shotWeights: {
          "shot-hidra-power": 7,
          "shot-ojos-fresh": 3,
        },
        moodWeights: { Hydrated: 7 },
      },
      {
        id: "opt_mood_firm",
        questionId: "q_skin_mood",
        label: "Firm & Tersa",
        description: "Textura lisa, mirada descansada y prevención pro-edad.",
        icon: "🪄",
        value: "Firm",
        shotWeights: {
          "shot-piel-smooth": 6,
          "shot-ojos-fresh": 5,
        },
        moodWeights: { Firm: 7 },
      },
    ],
  },
  {
    id: "q_routine_experience",
    order: 4,
    title: "¿Qué tipo de rutina se adapta mejor a tu estilo de vida?",
    subtitle: "Personalizamos los pasos recomendados a tu tiempo diario.",
    type: "single",
    active: true,
    options: [
      {
        id: "opt_rt_essential",
        questionId: "q_routine_experience",
        label: "Rutina Esencial (3 pasos)",
        description: "Limpieza, Shot concentrado de tratamiento y Protección solar.",
        icon: "⚡",
        value: "essential",
        shotWeights: {
          "shot-hidra-power": 2,
          "shot-piel-tranquila": 2,
        },
        moodWeights: {},
      },
      {
        id: "opt_rt_ritual",
        questionId: "q_routine_experience",
        label: "Ritual Completo K-Beauty (4-5 pasos)",
        description: "Doble limpieza/tónico, Shot focalizado, hidratante y contorno/SPF.",
        icon: "🧖‍♀️",
        value: "complete",
        shotWeights: {
          "shot-ojos-fresh": 3,
          "shot-piel-smooth": 3,
          "shot-adios-manchitas": 3,
        },
        moodWeights: { Glow: 2, Firm: 2 },
      },
    ],
  },
];
